version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # http://localhost:6333/dashboard#/collections
      - "6334:6334"

